#!/bin/bash

# Add official postgres repository
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

# Add neovim repository
sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install neovim

# Add commercial haskell's stack package manager
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442
sudo sh -c 'echo "deb http://download.fpcomplete.com/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/fpco.list'

# Update
sudo apt-get update
sudo apt-get upgrade

# Install everything
sudo apt-get install software-properties-common
sudo apt-get install python-dev python-pip python3-dev python3-pip
sudo apt-get install wget ca-certificates
sudo apt-get install postgresql-9.5 
sudo apt-get install nginx
sudo apt-get install stack

